language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install coveralls
  - pip install -e .[dev]

script:
  - py.test tests --cov click_plugins --cov-report term-missing

after_success:
  - coveralls
